name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [3.10, 3.11, 3.12]
        os: [ubuntu-latest, windows-latest, macos-14]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.version}}
        
